[global]
# The input file
# If you don't specify a full path, it will be interpreted as relative to the executable program directory
input_file = "getbits_20230401_195315_RAW_BITS.BIN"
bool_test_NIST = true
bool_statistical_analysis = false
# Select which tests to test IID assumption
test_list_indexes = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# step in reading bin file
# calculated as n_symbols/2
# step = 500

[nist_test]
n_symbols = 1000
n_sequences = 100000
# if True: FY shuffle
# if False: use random sampling from file
bool_shuffle_NIST = true
# if True: reference sequence read from beginning
# if False: reference sequence from the end
bool_first_seq = true
# if True: the NIST values are set
# if False: the user chooses value
bool_pvalue = false
see_plots = false
# NIST values
p = [1, 2, 8, 16, 32]

[statistical_analysis]
n_sequences_stat = 200
n_symbols_stat = 1000
n_iterations_c_stat = 500
# Select which test index for counter distribution
distribution_test_index = 6
# if True: FY shuffle,
# if False: use random sampling from file
bool_shuffle_stat = true
# User sets preferred value
p_value_stat = 2
# Select which test indexes for shuffle/random comparison
ref_numbers = [1, 3, 4]