name: Black

on:
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/black.yml"
      - ".github/workflows/flake8.yml"
  push:
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/black.yml"
      - ".github/workflows/flake8.yml"


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: psf/black@stable
        with:
          options: "--check --diff --color --line-length 119"
