name: flake8

on:
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/black.yml"
      - ".github/workflows/flake8.yml"
  push:
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/black.yml"
      - ".github/workflows/flake8.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v5
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E203,E701,W503"
          max-line-length: "120"